version: "3.9"

services:

  # Traefik reverse proxy & SSL management.
  traefik:
    image: "traefik:2.4"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web-secure.address=:443"
      - "--certificatesresolvers.resolver.acme.httpchallenge=true"
      - "--certificatesresolvers.resolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.resolver.acme.email=git.kwzrd@gmail.com"
      - "--certificatesresolvers.resolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  # Gunicorn serving our Flask app.
  kwzrd-site:
    image: "kwzrd/kwzrd-site:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kwzrd-site.rule=Host(`kwzrd.site`)"
      - "traefik.http.routers.kwzrd-site.entrypoints=web-secure"
      - "traefik.http.routers.kwzrd-site.tls.certresolver=resolver"
