name: "Deployment"

on:
  workflow_run:
    workflows:
      - "Build & Push"
    branches:
      - "main"
    types:
      - "completed"

jobs:
  deploy:
    name: "Deploy to Kubernetes"
    runs-on: "ubuntu-18.04"

    steps:
      - name: "Checkout Kube manifests"
        uses: "actions/checkout@v2"
        with:
          repository: "kwzrd/kube-manifest"
          ref: "main"
          token: "${{ secrets.KUBE_MANIFEST_TOKEN }}"

      - name: "K8s: set context"
        uses: "azure/k8s-set-context@v1"
        with:
          method: "kubeconfig"
          kubeconfig: "${{ secrets.KUBECONFIG }}"

      - name: "K8s: deploy manifest"
        uses: "azure/k8s-deploy@v1"
        with:
          manifests: "kube-manifest/kwzrd-site/deployment.yml"
          images: "ghcr.io/kwzrd/kwzrd-site:latest"
